In [1]:
# Exemple d'arbre de décision avec Mushroom
# Importation des bibliothèques nécessaires
from ucimlrepo import fetch_ucirepo 
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import CategoricalNB
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
import numpy as np

# Importation des données Mushroom du répertoire UCI
mushroom = fetch_ucirepo(id=73) 
# metadata 
print(mushroom.metadata)
# Extraction des variables prédictives et cible sous forme de Dataframe
X_dataframe = mushroom.data.features 
y_dataframe = mushroom.data.targets 

{'uci_id': 73, 'name': 'Mushroom', 'repository_url': 'https://archive.ics.uci.edu/dataset/73/mushroom', 'data_url': 'https://archive.ics.uci.edu/static/public/73/data.csv', 'abstract': 'From Audobon Society Field Guide; mushrooms described in terms of physical characteristics; classification: poisonous or edible', 'area': 'Biology', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 8124, 'num_features': 22, 'feature_types': ['Categorical'], 'demographics': [], 'target_col': ['poisonous'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 1981, 'last_updated': 'Thu Aug 10 2023', 'dataset_doi': '10.24432/C5959T', 'creators': [], 'intro_paper': None, 'additional_info': {'summary': "This data set includes descriptions of hypothetical samples corresponding to 23 species of gilled mushrooms in the Agaricus and Lepiota Family (pp. 500-525).  Each species is identified as definitely edible, definitely po

In [2]:
# Encodage des variables textuelles en entiers pour categoricalNB()
encodeur_X = LabelEncoder()
X=X_dataframe.to_numpy()
X_encode = np.array([encodeur_X.fit_transform(v) for v in X.T]).T
print("X:")
print(X[0:4])
print("X encodé:")
print(X_encode[0:4])

# Encodage des étiquettes textuelles en entiers
encodeur_y = LabelEncoder()
y=y_dataframe.iloc[:, 0].to_numpy()
y_encode = encodeur_y.fit_transform(y)
print("y:")
print(y[0:4])
print("y encodé:")
print(y_encode[0:4])

X:
[['x' 's' 'n' 't' 'p' 'f' 'c' 'n' 'k' 'e' 'e' 's' 's' 'w' 'w' 'p' 'w' 'o'
  'p' 'k' 's' 'u']
 ['x' 's' 'y' 't' 'a' 'f' 'c' 'b' 'k' 'e' 'c' 's' 's' 'w' 'w' 'p' 'w' 'o'
  'p' 'n' 'n' 'g']
 ['b' 's' 'w' 't' 'l' 'f' 'c' 'b' 'n' 'e' 'c' 's' 's' 'w' 'w' 'p' 'w' 'o'
  'p' 'n' 'n' 'm']
 ['x' 'y' 'w' 't' 'p' 'f' 'c' 'n' 'n' 'e' 'e' 's' 's' 'w' 'w' 'p' 'w' 'o'
  'p' 'k' 's' 'u']]
X encodé:
[[5 2 4 1 6 1 0 1 4 0 2 2 2 7 7 0 2 1 4 2 3 5]
 [5 2 9 1 0 1 0 0 4 0 1 2 2 7 7 0 2 1 4 3 2 1]
 [0 2 8 1 3 1 0 0 5 0 1 2 2 7 7 0 2 1 4 3 2 3]
 [5 3 8 1 6 1 0 1 5 0 2 2 2 7 7 0 2 1 4 2 3 5]]
y:
['p' 'e' 'e' 'p']
y encodé:
[1 0 0 1]


In [3]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report
classifieur = DecisionTreeClassifier()
classifieur.fit(X_encode, y_encode)
y_pred = classifieur.predict(X_encode)
accuracy = accuracy_score(y_encode, y_pred)
print("Taux de bonnes réponses:", accuracy)

Taux de bonnes réponses: 1.0
