In [10]:
# Importation des bibliothèques nécessaires
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import CategoricalNB
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report
import numpy as np

# Variables sexe,âge et revenu
X = np.array(
[
    ["m",	"jeune",	"faible"],
    ["m",	"jeune",	"élevé"],
    ["f",	"jeune",	"élevé"],
    ["m",	"jeune",	"faible"],
    ["f",	"vieux",	"élevé"],
    ["f",	"vieux",	"faible"],
    ["f",	"jeune",	"faible"],
    ["m",	"vieux",	"élevé"],
    ["m",	"vieux",	"faible"],
    ["f",	"vieux",	"faible"],
])

# Oui pour joueur
y_text = np.array(["non", "oui", "oui", "oui", "non", 
                   "non", "non", "oui", "non", "non"])

# Encodage des variables prédictives sous forme d'entiers pour le classifieur CategoricalNB()
encodeur_X = LabelEncoder()
X_encode = np.array([encodeur_X.fit_transform(v) for v in X.T]).T
print("X encodé:")
print(X_encode)

# Encodage des étiquettes textuelles
encodeur_y = LabelEncoder()
y_encode = encodeur_y.fit_transform(y_text)
print("y encodé:")
print(y_encode)

# Création du classifieur bayésien naïf pour les données catégoriques
classifieur = CategoricalNB()

# Entraînement du modèle sur les données complètes
classifieur.fit(X_encode, y_encode)

# Prédictions pour toutes les données
y_pred_encode = classifieur.predict(X_encode)
print("y_pred_encode:",y_pred_encode)

# Évaluation de la précision du modèle
print("Taux de bonnes réponses:", accuracy_score(y_encode, y_pred_encode))
rapport=classification_report(y_encode,y_pred_encode)
print("Rapport de classification:")
print(classification_report(y_encode,y_pred_encode))

# Décodage des étiquettes prédites
y_pred_text = encodeur_y.inverse_transform(y_pred_encode)

# Affichage des résultats de prédiction
print("Étiquettes réelles : ", encodeur_y.inverse_transform(y_encode))
print("Étiquettes prédites : ", y_pred_text)


X encodé:
[[1 0 0]
 [1 0 1]
 [0 0 1]
 [1 0 0]
 [0 1 1]
 [0 1 0]
 [0 0 0]
 [1 1 1]
 [1 1 0]
 [0 1 0]]
y encodé:
[0 1 1 1 0 0 0 1 0 0]
y_pred_encode: [0 1 1 0 0 0 0 1 0 0]
Taux de bonnes réponses: 0.9
Rapport de classification:
              precision    recall  f1-score   support

           0       0.86      1.00      0.92         6
           1       1.00      0.75      0.86         4

    accuracy                           0.90        10
   macro avg       0.93      0.88      0.89        10
weighted avg       0.91      0.90      0.90        10

Étiquettes réelles :  ['non' 'oui' 'oui' 'oui' 'non' 'non' 'non' 'oui' 'non' 'non']
Étiquettes prédites :  ['non' 'oui' 'oui' 'non' 'non' 'non' 'non' 'oui' 'non' 'non']
