In [5]:
import numpy as np
import random

gamma = 1 # taux d'escompte
taille_grille = 4
recompense = -1
etats_terminaux = [[0,0], [taille_grille-1, taille_grille-1]]
actions = [[-1, 0], [1, 0], [0, 1], [0, -1]]
nombre_iterations = 1000

def p(s,a):
    """ Retourne l'état suivant s_prime et la récompense r"""
    if s in etats_terminaux:
        return s, 0
    s_prime = np.array(s) + np.array(a)
    r = recompense
    # si débordement de grille retour à l'état s
    if -1 in s_prime or taille_grille in s_prime:
        s_prime = s
    return s_prime, r

# Initialize valueMap and valueMap1
v = np.zeros((taille_grille, taille_grille))
etats = [[i, j] for i in range(taille_grille) for j in range(taille_grille)]

def calculer_v_par_iteration(etats,actions,nombre_iterations,gamma,v):
    for i in range(nombre_iterations):
        copie_v=np.copy(v)
        delta = 0
        for etat in etats :
            moyenne_v=0
            for action in actions:
                s_prime,r = p(etat,action)
                moyenne_v += 1/len(actions)* (r + gamma * v[s_prime[0],s_prime[1]])
            copie_v[etat[0],etat[1]]=moyenne_v
            delta =max(delta,abs(moyenne_v-v[etat[0],etat[1]]))
        v = np.copy(copie_v)
        if(delta < 0.01):                                                
            print(v)
            break
            
calculer_v_par_iteration(etats,actions,1000,1,v)

[[  0.         -13.89528403 -19.84482978 -21.82635535]
 [-13.89528403 -17.86330422 -19.84586777 -19.84482978]
 [-19.84482978 -19.84586777 -17.86330422 -13.89528403]
 [-21.82635535 -19.84482978 -13.89528403   0.        ]]
