In [1]:
import numpy as np
import random

def sigmoide(z):
    """La fonction d'activation sigmoide"""
    return 1.0/(1.0+np.exp(-z))

def sigmoide_derivee(z):
    """Derivative of the sigmoid function."""
    return sigmoide(z)*(1-sigmoide(z))

nc = (2,3,1)
nombre_couches = len(nc)
""" 
Creer un tableau de matrices de poids w, weights[0] est un tableau 2D des poids entre
la couche 0 et la couche 1"""
w = [np.random.randn(x+1, y) for x, y in zip(nc[:-1], nc[1:])]
a=np.ones((3,1))
for wc in w:
    a = np.vstack((np.ones(1),sigmoide(np.dot(wc.transpose(), a))))
    print(a)

[[1.        ]
 [0.79466589]
 [0.10115763]
 [0.83990523]]
[[1.        ]
 [0.21416201]]


In [2]:
w

[array([[ 1.12308979, -1.63329405,  1.04385942],
        [ 1.77549755, -0.76782233,  0.90934662],
        [-1.54530402,  0.21668873, -0.29568292]]), array([[-0.96816726],
        [ 1.83213615],
        [-1.21622511],
        [-1.98207628]])]

In [4]:
def derivee_cout(output_activations, y):
    """ Vecteur des dérivées de la fonction de cout vs aj"""
    return (output_activations-y)


nabla_w = [np.zeros(wc.shape) for wc in w]
# feedforward
x=np.ones((2,1))
print(x,type(x))
print(x.ndim)
activation = np.vstack((np.ones(1),x))
activations = [np.vstack((np.ones(1),x))] # list to store all the activations, layer by layer
zs = [] # list to store all the z vectors, layer by layer

for wc in w:
    z = np.dot(wc.transpose(), activation)
    zs.append(z)
    activation = np.vstack((np.ones(1),sigmoide(z))) 
    activations.append(activation)
print("activations:",activations)
print("zs",zs)

[[1.]
 [1.]] <class 'numpy.ndarray'>
2
activations: [array([[1.],
       [1.],
       [1.]]), array([[1.        ],
       [0.79466589],
       [0.10115763],
       [0.83990523]]), array([[1.        ],
       [0.21416201]])]
zs [array([[ 1.35328333],
       [-2.18442765],
       [ 1.65752311]]), array([[-1.30001784]])]


In [6]:
# backward pass 
# delta est la dérivée par rapport zjc-1
# calcul de la dérivée par rapport a z pour la couche de sortie
y = np.ones(1)
delta = derivee_cout(activations[-1][1:], y) * sigmoide_derivee(zs[-1])
print("delta couche[2]:",delta)
# nabla_b[-1] = delta
nabla_w[-1] = np.dot(activations[-2],delta)
print("del w couche[2]:",nabla_w[-1])

        # Note that the variable l in the loop below is used a little
        # differently to the notation in Chapter 2 of the book.  Here,
        # l = 1 means the last layer of neurons, l = 2 is the
        # second-last layer, and so on.  It's a renumbering of the
        # scheme in the book, used here to take advantage of the fact
        # that Python can use negative indices in lists.
for l in range(2, nombre_couches):
    z = zs[-l]
    sp = sigmoide_derivee(z)
    print("deriveeSigmoide sp:",sp)
    print("w[-l+1]:",w[-l+1])
    print("w*delta:", np.dot(w[-l+1], delta))
    delta = np.dot(w[-l+1], delta)[1:] * sp
    print("delta nouveau:",delta)
# nabla_b[-l] = delta
    nabla_w[-l] = np.dot(delta, activations[-l-1].transpose())
    print("nabla_w nouveau:",nabla_w[-l])
print("nabla_w:",nabla_w)

delta couche[2]: [[-0.0167032]]
del w couche[2]: [[-0.0167032 ]
 [-0.01124126]
 [-0.01364156]
 [-0.00909036]]
deriveeSigmoide sp: [[0.22007086]
 [0.14969889]
 [0.24804381]]
w[-l+1]: [[0.4116284 ]
 [0.43508163]
 [1.2740292 ]
 [0.13984373]]
w*delta: [[-0.00687551]
 [-0.00726726]
 [-0.02128037]
 [-0.00233584]]
delta nouveau: [[-0.00159931]
 [-0.00318565]
 [-0.00057939]]
nabla_w nouveau: [[-0.00159931 -0.00159931 -0.00159931]
 [-0.00318565 -0.00318565 -0.00318565]
 [-0.00057939 -0.00057939 -0.00057939]]
nabla_w: [array([[-0.00159931, -0.00159931, -0.00159931],
       [-0.00318565, -0.00318565, -0.00318565],
       [-0.00057939, -0.00057939, -0.00057939]]), array([[-0.0167032 ],
       [-0.01124126],
       [-0.01364156],
       [-0.00909036]])]


In [10]:
print("w:",w)
eta = 0.1
w = [wc-eta*nwc for wc, nwc in zip(w, nabla_w)]
print("w:",w)

w: [array([[ 0.21403027,  1.78251735,  0.22509387],
       [-1.35144146,  0.86884416, -0.17368114],
       [ 1.85973457, -1.15665395,  0.12650259]]), array([[0.41329872],
       [0.43620576],
       [1.27539335],
       [0.14075277]])]
w: [array([[ 0.2141902 ,  1.78267728,  0.2252538 ],
       [-1.35112289,  0.86916273, -0.17336257],
       [ 1.8597925 , -1.15659601,  0.12656053]]), array([[0.41496904],
       [0.43732988],
       [1.27675751],
       [0.14166181]])]
